namespace: dseeley

name: blockdevmap

version: 0.0.0       # This is automatically filled by Jenkins on galaxy release with the current git release tag number.

readme: README.md

authors:
- Dougal Seeley <github@dougalseeley.com>

description: An Ansible module to map cloud-specific (AWS, GCP, Azure, LibVirt) block device names (e.g. /dev/sdf) with the volume provided to the OS.

#license:
#- BSD-3-Clause

license_file: 'LICENSE'

tags: ['aws', 'gcp', 'azure', 'libvirt', 'storage', 'system']

dependencies: {}

repository: https://github.com/dseeley/blockdevmap

documentation: https://github.com/dseeley/blockdevmap/blob/master/README.md

homepage: https://github.com/dseeley/blockdevmap

issues: https://github.com/dseeley/blockdevmap/issues

build_ignore: [ '.idea', '.gitignore', 'Dockerfile*' ]

